[default]
name = OpenSSH SECURITY HARDENER 
description =  This program hardens an OpenSSH server based on various templates
contexts = webserver, backupserver

[webserver]
;system_path = /etc/ssh/sshd_config
system_path = sshd_config-sample
template_path = contexts/context_webserver
template_compiler_path = contexts/context_webserver.csv
restart_cmd = systemctl restart ssh.service

[backupserver]
;system_path = /etc/ssh/sshd_config
system_path = sshd_config-sample
template_path = contexts/context_backupserver
template_compiler_path = contexts/context_backupserver.csv
restart_cmd = systemctl restart ssh.service
